security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # les urls auxquels s'appliquent ce firewall, dans ce cas, ce sont toutes les urls
            pattern: ^/

            # La connexion n'est pas requise sur toutes les pages
            # par exemple la page d'accueil
            anonymous: true
            
            form_login:
                login_path: login
                check_path: login

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            logout:
                # La route o√π se trouve le process de deconnexion
                path: logout
                # La route sur laquelle doit etre rediriger l'utilisateur apres une deconnexion
                target: login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register-confirmation, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil$, role: ROLE_USER }
        - { path: ^/upload, role: ROLE_USER }
        - { path: ^/download, role: ROLE_USER }
        - { path: ^/files, role: ROLE_USER }
        - { path: ^/categories, role: ROLE_USER }
        - { path: ^/delete, role: ROLE_USER }
        - { path: ^/admin/role, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
